//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperStoreProject {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class az {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal az() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperStoreProject.az", typeof(az).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artir.
        /// </summary>
        internal static string btn_artir {
            get {
                return ResourceManager.GetString("btn_artir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        internal static string btn_axtar {
            get {
                return ResourceManager.GetString("btn_axtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        internal static string btn_axtar_ad {
            get {
                return ResourceManager.GetString("btn_axtar_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        internal static string btn_axtar_kateqoriya {
            get {
                return ResourceManager.GetString("btn_axtar_kateqoriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axtar.
        /// </summary>
        internal static string btn_axtar_stok {
            get {
                return ResourceManager.GetString("btn_axtar_stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bax.
        /// </summary>
        internal static string btn_bax {
            get {
                return ResourceManager.GetString("btn_bax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bərpa Kodu.
        /// </summary>
        internal static string btn_berpa_kodu {
            get {
                return ResourceManager.GetString("btn_berpa_kodu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butun.
        /// </summary>
        internal static string btn_butun {
            get {
                return ResourceManager.GetString("btn_butun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butun Mehsullar.
        /// </summary>
        internal static string btn_butun_mehsullar {
            get {
                return ResourceManager.GetString("btn_butun_mehsullar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Butun Satislar.
        /// </summary>
        internal static string btn_butun_satislar {
            get {
                return ResourceManager.GetString("btn_butun_satislar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil Et.
        /// </summary>
        internal static string btn_daxil_et {
            get {
                return ResourceManager.GetString("btn_daxil_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daxil Ol.
        /// </summary>
        internal static string btn_daxilol {
            get {
                return ResourceManager.GetString("btn_daxilol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elave Et.
        /// </summary>
        internal static string btn_elave_et {
            get {
                return ResourceManager.GetString("btn_elave_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassir.
        /// </summary>
        internal static string btn_kassir {
            get {
                return ResourceManager.GetString("btn_kassir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassir Melumatlari.
        /// </summary>
        internal static string btn_kassir_melumatlari {
            get {
                return ResourceManager.GetString("btn_kassir_melumatlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menecer.
        /// </summary>
        internal static string btn_menecer {
            get {
                return ResourceManager.GetString("btn_menecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satici.
        /// </summary>
        internal static string btn_satici {
            get {
                return ResourceManager.GetString("btn_satici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satici Melumatlari.
        /// </summary>
        internal static string btn_satici_melumatlari {
            get {
                return ResourceManager.GetString("btn_satici_melumatlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        internal static string btn_satis {
            get {
                return ResourceManager.GetString("btn_satis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıfırla.
        /// </summary>
        internal static string btn_sifirla {
            get {
                return ResourceManager.GetString("btn_sifirla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        internal static string btn_sil {
            get {
                return ResourceManager.GetString("btn_sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Kassir.
        /// </summary>
        internal static string btn_yeni_kassir {
            get {
                return ResourceManager.GetString("btn_yeni_kassir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Satici.
        /// </summary>
        internal static string btn_yeni_satici {
            get {
                return ResourceManager.GetString("btn_yeni_satici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yenile.
        /// </summary>
        internal static string btn_yenile {
            get {
                return ResourceManager.GetString("btn_yenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Tarixe Gore.
        /// </summary>
        internal static string gb_2_tarix {
            get {
                return ResourceManager.GetString("gb_2_tarix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ada Gore Axtar.
        /// </summary>
        internal static string gb_axtar {
            get {
                return ResourceManager.GetString("gb_axtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isci Melumatlarini Yenile.
        /// </summary>
        internal static string gb_isci_melumatlari {
            get {
                return ResourceManager.GetString("gb_isci_melumatlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isciler.
        /// </summary>
        internal static string gb_isciler {
            get {
                return ResourceManager.GetString("gb_isciler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassir.
        /// </summary>
        internal static string gb_kassir {
            get {
                return ResourceManager.GetString("gb_kassir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassirler.
        /// </summary>
        internal static string gb_kassirler {
            get {
                return ResourceManager.GetString("gb_kassirler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriyaya Gore Axtar.
        /// </summary>
        internal static string gb_kateqoriya {
            get {
                return ResourceManager.GetString("gb_kateqoriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehsullar.
        /// </summary>
        internal static string gb_mehsullar {
            get {
                return ResourceManager.GetString("gb_mehsullar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satici.
        /// </summary>
        internal static string gb_satici {
            get {
                return ResourceManager.GetString("gb_satici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saticilar.
        /// </summary>
        internal static string gb_saticilar {
            get {
                return ResourceManager.GetString("gb_saticilar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış.
        /// </summary>
        internal static string gb_satis {
            get {
                return ResourceManager.GetString("gb_satis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satis Sil.
        /// </summary>
        internal static string gb_satis_sil {
            get {
                return ResourceManager.GetString("gb_satis_sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satislar.
        /// </summary>
        internal static string gb_satislar {
            get {
                return ResourceManager.GetString("gb_satislar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok Artir.
        /// </summary>
        internal static string gb_stok_artir {
            get {
                return ResourceManager.GetString("gb_stok_artir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarixe Gore.
        /// </summary>
        internal static string gb_tarix {
            get {
                return ResourceManager.GetString("gb_tarix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Mehsul Elave Et.
        /// </summary>
        internal static string gb_yeni_mehsul {
            get {
                return ResourceManager.GetString("gb_yeni_mehsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad :.
        /// </summary>
        internal static string lbl_ad {
            get {
                return ResourceManager.GetString("lbl_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string lbl_adsoyad {
            get {
                return ResourceManager.GetString("lbl_adsoyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alis :.
        /// </summary>
        internal static string lbl_alis {
            get {
                return ResourceManager.GetString("lbl_alis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Kat :.
        /// </summary>
        internal static string lbl_alt_kat {
            get {
                return ResourceManager.GetString("lbl_alt_kat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email :.
        /// </summary>
        internal static string lbl_email {
            get {
                return ResourceManager.GetString("lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id :.
        /// </summary>
        internal static string lbl_id {
            get {
                return ResourceManager.GetString("lbl_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istehsalci :.
        /// </summary>
        internal static string lbl_istehsalci {
            get {
                return ResourceManager.GetString("lbl_istehsalci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassir :.
        /// </summary>
        internal static string lbl_kassir {
            get {
                return ResourceManager.GetString("lbl_kassir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassir No:.
        /// </summary>
        internal static string lbl_kassirno {
            get {
                return ResourceManager.GetString("lbl_kassirno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Kateqoriya :.
        /// </summary>
        internal static string lbl_kat_alt {
            get {
                return ResourceManager.GetString("lbl_kat_alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ust Kateqorya :.
        /// </summary>
        internal static string lbl_kat_ust {
            get {
                return ResourceManager.GetString("lbl_kat_ust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kateqoriya :.
        /// </summary>
        internal static string lbl_kateqoriya {
            get {
                return ResourceManager.GetString("lbl_kateqoriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maas :.
        /// </summary>
        internal static string lbl_maas {
            get {
                return ResourceManager.GetString("lbl_maas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id :.
        /// </summary>
        internal static string lbl_mehsul_id {
            get {
                return ResourceManager.GetString("lbl_mehsul_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehsul Id :.
        /// </summary>
        internal static string lbl_mehsulid {
            get {
                return ResourceManager.GetString("lbl_mehsulid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menecer.
        /// </summary>
        internal static string lbl_menecer {
            get {
                return ResourceManager.GetString("lbl_menecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menecer Sehifesi:.
        /// </summary>
        internal static string lbl_menecer_sehifesi {
            get {
                return ResourceManager.GetString("lbl_menecer_sehifesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menecer No :.
        /// </summary>
        internal static string lbl_menecerno {
            get {
                return ResourceManager.GetString("lbl_menecerno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pul :.
        /// </summary>
        internal static string lbl_pul {
            get {
                return ResourceManager.GetString("lbl_pul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qaliq :.
        /// </summary>
        internal static string lbl_qaliq {
            get {
                return ResourceManager.GetString("lbl_qaliq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymet :.
        /// </summary>
        internal static string lbl_qiymet {
            get {
                return ResourceManager.GetString("lbl_qiymet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad :.
        /// </summary>
        internal static string lbl_satici_ad {
            get {
                return ResourceManager.GetString("lbl_satici_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad :.
        /// </summary>
        internal static string lbl_satici_soyad {
            get {
                return ResourceManager.GetString("lbl_satici_soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satis :.
        /// </summary>
        internal static string lbl_satis {
            get {
                return ResourceManager.GetString("lbl_satis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satis Id :.
        /// </summary>
        internal static string lbl_satis_id {
            get {
                return ResourceManager.GetString("lbl_satis_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say :.
        /// </summary>
        internal static string lbl_say {
            get {
                return ResourceManager.GetString("lbl_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sifre :.
        /// </summary>
        internal static string lbl_sifre {
            get {
                return ResourceManager.GetString("lbl_sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Istifade Tarixi :.
        /// </summary>
        internal static string lbl_son_ist {
            get {
                return ResourceManager.GetString("lbl_son_ist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stok :.
        /// </summary>
        internal static string lbl_stok {
            get {
                return ResourceManager.GetString("lbl_stok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarix :.
        /// </summary>
        internal static string lbl_tarix {
            get {
                return ResourceManager.GetString("lbl_tarix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarix 1 :.
        /// </summary>
        internal static string lbl_tarix1 {
            get {
                return ResourceManager.GetString("lbl_tarix1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarix 2 :.
        /// </summary>
        internal static string lbl_tarix2 {
            get {
                return ResourceManager.GetString("lbl_tarix2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təkrar :.
        /// </summary>
        internal static string lbl_tekrar {
            get {
                return ResourceManager.GetString("lbl_tekrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon :.
        /// </summary>
        internal static string lbl_telefon {
            get {
                return ResourceManager.GetString("lbl_telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam :.
        /// </summary>
        internal static string lbl_toplam {
            get {
                return ResourceManager.GetString("lbl_toplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ust Kat :.
        /// </summary>
        internal static string lbl_ust_kat {
            get {
                return ResourceManager.GetString("lbl_ust_kat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yekun Qiymet :.
        /// </summary>
        internal static string lbl_yekun {
            get {
                return ResourceManager.GetString("lbl_yekun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Şifrə :.
        /// </summary>
        internal static string lbl_yeni_sifre {
            get {
                return ResourceManager.GetString("lbl_yeni_sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrəmi Unutdum.
        /// </summary>
        internal static string lnk_lbl_sifreberpa {
            get {
                return ResourceManager.GetString("lnk_lbl_sifreberpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MehsulAdi.
        /// </summary>
        internal static string lv_mehsul_ad {
            get {
                return ResourceManager.GetString("lv_mehsul_ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiymət.
        /// </summary>
        internal static string lv_mehsul_qiymet {
            get {
                return ResourceManager.GetString("lv_mehsul_qiymet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say.
        /// </summary>
        internal static string lv_mehsul_say {
            get {
                return ResourceManager.GetString("lv_mehsul_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam.
        /// </summary>
        internal static string lv_mehsul_toplam {
            get {
                return ResourceManager.GetString("lv_mehsul_toplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100&apos;den az.
        /// </summary>
        internal static string rb_100 {
            get {
                return ResourceManager.GetString("rb_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200&apos;den az.
        /// </summary>
        internal static string rb_200 {
            get {
                return ResourceManager.GetString("rb_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassir Nömrəsi.
        /// </summary>
        internal static string tb_kassirno {
            get {
                return ResourceManager.GetString("tb_kassirno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menecer Nömrəsi.
        /// </summary>
        internal static string tb_menecerno {
            get {
                return ResourceManager.GetString("tb_menecerno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elave Et Mehsul.
        /// </summary>
        internal static string tbc_elave_et_mehsul {
            get {
                return ResourceManager.GetString("tbc_elave_et_mehsul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isci Elave Et.
        /// </summary>
        internal static string tbc_isci_elave_et {
            get {
                return ResourceManager.GetString("tbc_isci_elave_et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isciler.
        /// </summary>
        internal static string tbc_isciler {
            get {
                return ResourceManager.GetString("tbc_isciler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kassa.
        /// </summary>
        internal static string tbc_kassa {
            get {
                return ResourceManager.GetString("tbc_kassa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehsullar.
        /// </summary>
        internal static string tbc_mehsullar {
            get {
                return ResourceManager.GetString("tbc_mehsullar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satislar.
        /// </summary>
        internal static string tbc_satislar {
            get {
                return ResourceManager.GetString("tbc_satislar", resourceCulture);
            }
        }
    }
}
